// js/parole-valide.js — Le parole di cinque lettere accettate come tentativo
// nella "Parola del giorno" (5166 parole, senza accenti).
//
// Fonti: l'elenco delle parole italiane di wordfreq (Robyn Speer, dati con
// licenza CC BY-SA 4.0) e an-array-of-italian-words (licenza MIT), tenendo
// solo le parole riconosciute dal dizionario italiano di LibreOffice.
// Questo elenco si puo' riusare con la stessa licenza CC BY-SA 4.0.
(function (root, factory) {
  'use strict';
  var api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  if (root) root.ParoleValide = api;
})(typeof self !== 'undefined' ? self : globalThis, function () {
  'use strict';
  return (
    'abaco abate abati abbai abbia abete abeti abile abili abita abiti abito abusa abusi abuso acari acaro accia aceri acero ' +
    'acese acesi aceti aceto achea achee achei acheo acida acide acidi acido acile acili acini acino acori acqua acque acume ' +
    'acuta acute acuti acuto adagi addii addio adipe adira adire adiri adita aditi adito adiva adone adoni adora adori adoro ' +
    'adula aduli aduna aerea aeree aerei aereo affar afide afidi afnio afona afoni afono afosa afose afosi afoso agape agapi ' +
    'agata agate agave agavi aggio agile agili agire agita agite agiti agito agiva agivo aglio agone agoni aiola aiole aiuta ' +
    'aiuti aiuto aizza aizzi alala alali alami alani alano alare alari alata alate alati alato alava album alche alcol alcun ' +
    'alesa alesi alghe algia algie alias alibi alice alici alida alide alidi alino alita alite aliti alito allea allei alleo ' +
    'alone aloni alosa altea altee alter altra altre altri altro alula alvei alveo alzai alzar amaca amaci amala amale amali ' +
    'amalo amami amane amano amara amare amari amaro amasi amata amate amati amato amava amavi amavo ambia ambio ambra ambre ' +
    'ameba amebe amena amene ameni ameno amica amici amico amide amidi amido amino amnio amore amori ampia ampie ampio ampli ' +
    'anale anali anche ancia ancor andai andar anela aneli anelo aneto angli anglo anice anici anima anime animi animo annoi ' +
    'annua annue annui annuo anodi anodo anone ansar ansia ansie antri antro anuri aorta apice apici apina apine apnea apnee ' +
    'apoda apode apodi appia appio aprii aprir apule apuli apulo araba arabe arabi arabo araci arale arano arare arata arate ' +
    'arati arato arava arche archi ardea arder ardir ardua ardue ardui arduo areca arena arene areni areno argon argue arida ' +
    'aride aridi arido arino arnia arnie aroma aromi arpia arpie arqua aschi ascia ascio asili asilo asina asine asini asino ' +
    'asola asole aspra aspre aspri aspro assai aster astio astri astro atemi atomi atomo atona atone atoni atono atout atrii ' +
    'atrio attua attui audio aurea auree aurei aureo avana avano avara avare avari avaro avena avene aveni avere averi avete ' +
    'aveva avevi avevo avida avide avidi avido avila avile avita avite aviti avito avoca avola avole avoli avolo avori avrai ' +
    'avrei avuta avute avuti avuto avvia avvii avvio azera azere azeri azero azoto babau babbi babbo bacca bacco bachi bacia ' +
    'bacio bacon badar badge badia badie baffi baffo bagli bagna bagni bagno baita baite balba balbi balbo balda balde baldi ' +
    'baldo balia balie balla balle balli ballo balma balme balsa balta balza balze balzi balzo banca banco banda bande bandi ' +
    'bando banjo banna banni banno bantu barai barba barbe barbi barbo barca barco barda barde bardi bardo baria bario barra ' +
    'barre barri barro basai basar basca basco bassa basse bassi basso basta baste basti basto batch batik batta batte batti ' +
    'batto baule bauli bazar bazza beale beane beano beare beata beate beati beato becca becco beffa beffe beffi beghe begli ' +
    'beige belar belga belgi bella belle belli bello belva belve benda bende bendi bendo benna benne bente benti beola beole ' +
    'beone beoni beota beoti berci berla berle berli berlo bermi berne bersi berta berte berti bervi besse bessi beste besti ' +
    'bette betti beuta beute bevve bevvi bezzi bezzo biada biade biamo biche bieca bieco bieta biete biffi bighe bighi bigia ' +
    'bigie bigio bigli bigne bijou bilia bilie bimba bimbe bimbi bimbo binda binde bingo bioma biomi birba birbo birra birre ' +
    'birri birro bisca bisce bissa bissi bisso bitta bitte bitti bitto bivio bizza bizze bleah blesa bleso blitz blues bluff ' +
    'blusa bluse blush boari boaro boati boato bocca bocce bocci boema boeme boemi boemo boera boere boeri boero boghe bolge ' +
    'bolla bolle bolli bollo bolsa bolsi bolso bomba bombe bombi bombo bonus bonzi bonzo borda borde bordi bordo borea borgo ' +
    'boria borie borio borra borri borro borsa borse bosco bossa bossi bosso botri botro botta botte botti botto boxer bozza ' +
    'bozze bozzi bozzo braca brace braci brada brade bradi brado braga brage brago brama brame brami bramo brani brano brasa ' +
    'brasi brava brave bravi bravo breve brevi brida bride briga brigo brina brine brini brino broda brodi brodo bromo bruca ' +
    'bruci bruco brugo bruma brume bruna brune bruni bruno bruta brute bruti bruto buana bucce buche buchi buffa buffe buffi ' +
    'buffo bugia bugie bugli bugna bugne bugni bugno bulbi bulbo bulla bulle bulli bullo buona buone buoni buono burba burbe ' +
    'burla burle burli burlo burri burro busca busco bussa busse bussi busso busta buste busti busto butta butti butto buzzo ' +
    'bwana cablo cabra cabri cacao cacca cacce cacci cache cachi cacio cadde caddi cadei cader cagar caghi cagli cagna cagne ' +
    'calai calar calca calce calci calco calda calde caldi caldo calia calla calle calli callo calma calme calmi calmo calva ' +
    'calve calvi calvo calza calze calzi calzo cambi camma camme campa campi campo canda cande candi cando canea cangi canna ' +
    'canne canoa canoe canta canti canto capii capir cappa cappe cappi capra capre capri capro capta capti capto carda cardi ' +
    'cardo cargo caria carie cario carme carmi carne carni carpa carpe carpi carpo carri carro carta carte casba casca casco ' +
    'cassa casse cassi casso casta caste casti casto catch caule causa cause causi causo cauta caute cauti cauto cavai cavar ' +
    'cavea cavia cavie cazzi cazzo ceche cechi ceder cedri cedro cedui ceduo ceffi ceffo celia celie celio cella celle celta ' +
    'celte celti cenai cenar cenci cenge cenni cenno censi censo cento ceppa ceppi ceppo cerca cerci cerco cerea cerei cereo ' +
    'cerio cerri cerro certa certe certi certo cerva cerve cervi cervo cesio cespi cespo cessa cessi cesso cesta ceste cesti ' +
    'cesto cetra cetre check chela chele cheta chete cheti cheto chili chilo chimi chimo china chine chini chino ciana ciane ' +
    'ciani ciano cicca cicce cicli ciclo cieca cieco cieli cielo cifra cifre cigli cigni cigno cince cinga cinge cingi cinse ' +
    'cinsi cinta cinte cinti cinto cippi cippo cipro circa circe circo cirri cirro cispa cispe cista ciste cisti cisto citai ' +
    'citar ciuco clava clave clavi clavo cleri clero click clima climi cline clini clivo clona clone cloni clono cloro clown ' +
    'clvii coach coana coane cobra cocca cocce cocci cocco coesa coese coesi coeso coeva coeve coevi coevo coffa coffe cogli ' +
    'coiti coito colar colei colga colgo colla colle colli collo colma colme colmi colmo colon color colpa colpe colpi colpo ' +
    'colse colsi colta colte colti colto colui colza comma commi compi conca conce conci conda conde condi condo confa conga ' +
    'conia conii conio conta conte conti conto copia copie copio coppa coppe coppi coppo copra copre copri copro copta copte ' +
    'copti copto coque corba corbe corda corde corea coree cormi cormo corna corni corno corpi corpo corra corre corri corro ' +
    'corsa corse corsi corso corta corte corti corto corvi corvo cosca cosce cosci cosmo cosse cossi cosso costa coste costi ' +
    'costo cotta cotte cotti cotto cover cozza cozze cozzi cozzo crack crani crapa crasi crawl creai cream crear creda crede ' +
    'credi credo crema creme cremo crepa crepe crepi crepo cresi creso creta crete crine crini crisi croce croci croco croda ' +
    'crode croma crome cromo crono cross crown cruda crude crudi crudo cruna cubia cucce cucci cucco cucia cucio culla culle ' +
    'culli cullo culmi culmo culpa culti culto cunei cuneo cuoca cuoce cuoci cuoco cuoia cuoio cuore cuori curai curar curda ' +
    'curde curdi curdo curia curie curio curry curva curve curvi curvo cviii cxiii cxvii cxxii cxxiv cxxix cxxvi cxxxi cxxxv ' +
    'dacci dacia dacie daghe dagli daini daino dalia dalla dalle dallo dammi dance danda dande dando dandy danna danne danni ' +
    'danno dante danti danza danze danzi danzo darai darci dardi dardo darei darla darle darli darlo darmi darne darsi darti ' +
    'darvi datar datti dazio debba debbi debbo degli degna degne degni degno della delle dello delta demmo denim densa dense ' +
    'densi denso dente denti depor derby derma dermi desco desio desse dessi desso desta deste desti desto detta dette detti ' +
    'detto devia devii devio diade diamo diana diane diano diari diate dicci dicco dieci diede diedi dieta diete dighe digli ' +
    'dildo dilla dille dilli dillo dimmi dingo dinne diodi diodo dipoi dirai dirci direi dirla dirle dirli dirlo dirmi dirne ' +
    'dirsi dirti dirvi disco disfa disfo disio disse dissi dista disti disto ditta ditte doble docce doghe dogli dogma dogmi ' +
    'dolce dolci dolga dolgo dolio dolse domai domar domma domme donai donar donde donna donne doppi dorma dorme dormi dormo ' +
    'dorsi dorso dossi dosso dotar dotta dotte dotti dotto dovei dover draga drago drena dreni dreno drink drive droga drogo ' +
    'drone droni druda drude drudi drudo drupa drupe drusa druse drusi druso duale duali dubat dubbi duchi duina dulia duole ' +
    'duolo duomi duomo durai durar durre duvet ebani ebano ebbra ebbre ebbri ebbro ebete ebeti ebola ebook ebrea ebree ebrei ' +
    'ebreo ecuba edema edemi edera edere edile edili edita edite editi edito educa educo edule eduli efebi efebo efori eforo ' +
    'egadi egida egide egira egizi egual eleni eleva elevi elevo elica elida elide elido elisa elise elisi eliso elogi elude ' +
    'elusa eluse elusi eluso email emana emani emano emici emico emina emine emiri emiro emise empia empie empio emula emule ' +
    'emuli emulo enter entra entri entro eolio epica epici epico epoca epodi epodo eppoi eppur eprom epura erano erari erbai ' +
    'erbio erebo erede eredi eremi eremo erger erica erige ernia ernie eroda erode eroga erosa erose erosi eroso esala esali ' +
    'esame esami esani esano esche esiga esige esigi esigo esile esili esima esime esimi esimo esita esiti esito esodi esodo ' +
    'esone esoni esosa esose esosi esoso espia espii espio essai esser estri estro esula esule esuli etano etera etere eteri ' +
    'etero ethos etica etici etico etile etimi etimo etnea etnee etnei etneo etnia etnie evada evade evadi evado evasa evase ' +
    'evasi evaso evira evita eviti evito evoca evoco extra facce facci facie facto fadda faggi fagli faida faide faina faine ' +
    'falbo falca falce falci falco falda falde faldi faldo falla falle falli fallo falsa false falsi falso fammi fanga fango ' +
    'fanne fanno fante fanti farad farai farce farci farei farla farle farli farlo farmi farne farri farro farsa farse farsi ' +
    'farti farvi fasce fasci fasti fasto fatta fatte fatti fatto fatua fatue fatui fatuo fauci fauna faune fauni fauno faure ' +
    'faust fauve fecce felce felci felpa felpe felze fende fendi fendo feria ferie ferii ferir ferma ferme fermi fermo ferra ' +
    'ferri ferro ferve fervi fervo fessa fesse fessi fesso festa feste fetta fette feudi feudo fiaba fiabe fiala fiale fiata ' +
    'fiati fiato fibra fibre ficca ficco fiche fichi ficus fidai fidar fidia fiele fieni fieno fiera fiere fieri fiero fifty ' +
    'fighe fighi figli filar filma filmi filmo filza filze finga finge fingi fingo finii finir finse finsi finta finte finti ' +
    'finto fioca fioco fiore fiori firma firme firmi firmo fisco fissa fisse fissi fisso fitta fitte fitti fitto fiume fiumi ' +
    'fiuta fiuti fiuto flash flati flato flava flavi flavo flebo flirt flora flore fobia fobie foche focus fodro fogge foggi ' +
    'foghe fogli fogna fogne fogno foiba foibe folio folla folle folli follo folta folte folti folto fonda fonde fondi fondo ' +
    'fonia fonte fonti forca forge forgi forma forme formi formo forni forno forra forre forse forte forti forum forza forze ' +
    'forzi forzo fosca fosco fossa fosse fossi fosso foste fosti fotta fotte fotti fotto fovea frame frana frane frani frano ' +
    'frase frasi frate frati frega fregi frego frema freme fremi fremo frena freni freno fresa frese fresi frigi frigo frine ' +
    'frisa frisi friso froci froda frode frodi frodo front fruga frugo fruir fuchi fugga fugge fuggi fuggo fughe fughi fulva ' +
    'fulve fulvi fulvo fumai fumar fummo funai funga funge fungi fungo funse funto fuoco fuori furba furbe furbi furbo furia ' +
    'furie furor furti furto fusco fusta fuste fusti fusto gabba gabbi gabbo gaffa gaffe galea galee galgo galla galle galli ' +
    'gallo gamba gambe gambi gambo gamma gamme ganci ganda ganga gangi ganze ganzi ganzo garba garbi garbo garni garra garre ' +
    'garri garro garza garze garzi garzo gasco gassa gatta gatte gatti gatto gauss gazza gazze gazzo gechi gelsi gelso gemer ' +
    'gemma gemme gemmi gemmo genia genie genio gente genti geode geodi gergo gerla gerle germe germi gessa gessi gesso gesta ' +
    'gesti gesto getta getti getto ghiri ghiro ghisa ghise giaca giace giaci giaco giada giade giara giare gibbo gighe gigli ' +
    'gilda gilde gilet ginna ginni gioca gioco giogo gioia gioie gioir giova giovi giovo girai girar gitta gitti gitto giuba ' +
    'giuda giura giuri giuro giuso gleba glebe glico glifi glifo globi globo glori gluma glume gnome gnomi gnomo gnosi gobba ' +
    'gobbe gobbi gobbo gocce goder godet goffa goffe goffi goffo gogna gogne golem golfi golfo golpe gomma gomme gommo gonfi ' +
    'gonna gonne gonza gonzi gonzo gorge gorgo gotta gotti gotto gozzi gozzo gradi grado grafi grafo grama grame grami gramo ' +
    'grana grane grani grano grata grate grati grato grava grave gravi grazi greca greci greco greti greto greve grevi grida ' +
    'gride gridi grido grifi grifo grige grigi grill grumi grumo guada guadi guado guaio guani guano guida guide guidi guido ' +
    'guisa guise gulag gusci gusta gusti gusto gutta hallo hanno harem hertz hindi hippy hobby hotel humus iarda iarde ibera ' +
    'iberi ibero iboga icona icone icono icore ictus idola idoli idolo idria igloo ignea ignee igneo ilare ilari ilota iloti ' +
    'imago imani imati imene imeni imita imiti imito impor inaco inala inali inalo inane inani india indie indio indir indur ' +
    'infra ingoi inizi input inuit invia invii invio iodio ioide ionia ionie ionio irata irate irati irato irica iride iridi ' +
    'irido iriti irosa iroso ischi islam isola isole isoli isolo issai issei istmi istmo itali italo itera itero jeans jolly ' +
    'joule jumbo karma kayak kefir koala krill labor lacca lacci lacco ladra ladre ladri ladro lager laghi lagna lagne lagni ' +
    'lagno laica laici laico laida laide laidi laido lamia lamie lampi lampo lance lanci landa lande lanzi lanzo lapin lapis ' +
    'lappa lappe lappi lardi lardo larga largo larva larve lasca lasci lasco laser lassa lasse lassi lasso latra latri latro ' +
    'latta latte latti lauda laude laudi laudo lauri lauro lauta laute lauti lauto lavai lavar lazza lazzi lazzo leale leali ' +
    'lecca lecci lecco leder legai legar legga legge leggi leggo leghe leghi legna legni legno lembi lembo lemma lemme lemmi ' +
    'lenci lenta lente lenti lento lenza lenze leone leoni lepre lepri lerce lerci lesbo lessa lesse lessi lesso lesta leste ' +
    'lesti lesto letta lette letti letto leuco leudo levai levar lezio lezzi lezzo liana liane libar libia libra libre libri ' +
    'libro licci licei liceo licia licio lieta liete lieti lieto lieve lievi ligia ligio lilla lilli limar limbo lince linci ' +
    'linda linde lindi lindo linea linee linfa linfe lippa lippe lisca lisce lisci lissa lisso lista liste listi listo litio ' +
    'litri litro lituo liuti liuto lizza lizze lobby lochi loden loess loffa logga logge loggo loghi logia logie login logli ' +
    'lolla lolle lombi lombo longa longo lonza lonze loppa lorda lorde lordi lordo losca losco lotta lotte lotti lotto lucci ' +
    'lucra lucri lucro lugli luigi lumen lunar lunga lungi lungo luogo lupus lusca lusco lussi lusso lutea luteo lutti lutto ' +
    'lviii lxiii lxvii lxxii lxxiv lxxix lxxvi lxxxi lxxxv macao macho macis macro madia madie madre madri mafia mafie maggi ' +
    'maghe maghi magia magie magio magli magma magmi magna magne magni magno magra magre magri magro malga malia malie malli ' +
    'mallo malta malte malti malto malva malve mambo mamma mamme manca mance manco manda mandi mando manga mangi mango mania ' +
    'manie manna manne manta mante manti manto manza manze manzi manzo maona maone maori mappa mappe mappo marca marce marci ' +
    'marco marea maree marmi marmo marna marne marni marno marra marre marza marze marzi marzo massa masse massi masso masti ' +
    'match mater matta matte matti matto maura maure mauri mauro mauve mazza mazze mazzi mazzo mdccl meati meato mecca media ' +
    'medie medio melma melme meloe menai menar mende mendi mendo mensa mense menta mente menti mento merce merci merda merde ' +
    'merla merli merlo mesce mesco messa messe messi messo mesta meste mesti mesto metal meteo meter metil metri metro metta ' +
    'mette metti metto mezza mezze mezzi mezzo miasi micce miche micia micie micio miele mieli mieta miete mieti mieto migra ' +
    'migri migro milio mille milza milze mimar minar minga mingo minia minio minor mioma miomi miope miopi miosi mirai mirar ' +
    'miria mirra mirti mirto missa missi misso mista miste misti misto mitra mitre mixer mocci mocio model modem modio modus ' +
    'moggi mogia mogie mogio mogli mogol moina moine moira moire molar molla molle molli mollo moloc molta molte molti molto ' +
    'monca monco monda monde mondi mondo monna monta monte monti monto morbi morbo morda morde mordi mordo morfo moria morie ' +
    'morii morir morra morsa morse morsi morso morta morte morti morto morva mosca mosce mosci mosco mossa mosse mossi mosso ' +
    'mosti mosto motel motta motte motti motto mouse mozza mozze mozzi mozzo mucca muchi muffa muffe mughi multa multe multi ' +
    'multo munda mundi munga munge mungi mungo munir munta munte munti munto muoia muoio muone muoni muore muori muova muove ' +
    'muovi muovo murai mural musco musei museo mussa mussi musso mutai mutar mutua mutue mutui mutuo nadir nafta nanna nanne ' +
    'nappa nappe nardi nardo narra narri narro nasca nasce nasci nasco naspi naspo nassa nasse natia natie natii natio natta ' +
    'natte nauta nauti nefro negai negar neghi negli negra negre negri negro negus nella nelle nello nembi nembo nemea nemei ' +
    'nemeo nenia nenie nenni nepal nerbo nervi nervo nesci nessi nesso nesta neste nesti nesto netta nette netti netto neuma ' +
    'neumi neuri neuro nevai nibbi nicol nient nievo nimbo ninfa ninfe ninja ninna ninne niobe nisba nissa nitra nitre nitro ' +
    'nivea niveo nobel nocca noema noemi nomea nonio nonna nonne nonni nonno noria norie norma norme normi normo notai notar ' +
    'notes notte notti nozze nubia nuche nulla nulle nulli nullo nummi nummo nunzi nuoce nuoci nuoco nuora nuore nuota nuoti ' +
    'nuoto nuova nuove nuovi nuovo nurse nutra nutre nutri nutro nylon obesa obese obesi obeso obice obici obito oblii oblio ' +
    'oboli obolo occhi oculi oculo odano oddio odeon odiai odiar odino odono odora odore odori odoro offra offre offri offro ' +
    'ofidi ofiti ogiva ogive oidio okapi oleum oligo oliva olive olivi olivo olmio olona olore oltre omana omane omani omano ' +
    'omari omasi omaso ombra ombre omega omeri omero omine omini omino omise omnia omone omoni omore omori oncia onera onere ' +
    'oneri onero onice onici onico onora onore onori onoro opaca opaco opale opali opera opere operi opero opima opina opini ' +
    'oppia oppio oppor optai orafa orafe orafi orafo orale orali orari orata orate orche orchi orcio orgia orgie orice orici ' +
    'orina orine orini orino ormai ornai orobi oropa osano osare osate osati osato osava osavi osavo oscar osche oschi osino ' +
    'osmio ossea ossee ossei osseo ossia ostar ostia ostie ostio ostri ostro otica otico otite otiti ovaia ovaie ovaio ovale ' +
    'ovali ovari ovata ovate ovati ovato ovest ovile ovili ovina ovine ovini ovino ovoli ovolo ovula ovuli ovulo ovvia ovvie ' +
    'ovvio ozena ozono pacca pacco pacem pachi padre padri paese paesi pagai pagar paggi paghe paghi palai palco paleo palio ' +
    'palla palle palli palma palme palmi palmo palpa palpi palpo pampa panca pance panda pania panie panna panne panni panno ' +
    'pansa panta pante pants panza paoli paolo pappa pappe pappi pappo papua parar parca parco pardi pardo parei pareo parer ' +
    'paria parie pario parka parke parla parli parlo parra parre parsa parse parsi parso parta parte parti parto party parve ' +
    'parvi pasca pasce pasci pasco passa passe passi passo pasta paste pasti pasto pater patia patii patio patir patos patri ' +
    'patta patte patti patto paura paure pausa pause pazza pazze pazzi pazzo peana pecca pecco pegni pegno pelle pelli pelta ' +
    'pelte pelvi penai penar pence penda pende pendi pendo penis penna penne penny pensa pensi penso penta pente penti pento ' +
    'peone peoni peplo pepsi perda perde perdi perdo perii perir perla perle perni perno persa perse persi perso pervi pesar ' +
    'pesca pesce pesci pesco pesos pesta peste pesti pesto petti petto pezza pezze pezzi pezzo piace piaci piaga piana piane ' +
    'piani piano picca picco picea piede piedi piega piego piena piene pieni pieno pieve pievi pigia pigio pigli pigna pigne ' +
    'pigra pigre pigri pigro pilaf pilar pileo pilla pilli pillo pince pinco pinna pinne pinot pinta pinte pinza pinze pinzi ' +
    'pinzo pioda piode pioli piolo pione pioni piota piova piove piovi pipia pippa pippe pirla pisce pisci pissi pista piste ' +
    'pitia pitta pitti pitto piuma piume pivot pixel pizia pizio pizza pizze pizzi pizzo placa placo plaga plage plagi plaid ' +
    'plana plani plano plebe plebi plica plico poche pochi podio poema poemi poeta poeti pogge poggi poker polca polio polis ' +
    'polka polke polla polle polli pollo polpa polpe polpi polpo polsi polso pomfi pomfo pompa pompe pompi pompo ponce ponci ' +
    'ponfi ponfo ponga pongo ponta ponte ponti ponto ponza ponzi ponzo poppa poppe poppi poppo porca porci porco porga porge ' +
    'porgi porgo porla porle porli porlo pormi porne porno porre porri porro porse porsi porta porte porti porto porvi posai ' +
    'posar possa posso posta poste posti posto potei poter poule pozza pozze pozzi pozzo praho praia prati prato prava pravi ' +
    'pravo prece preci preda prede predi predo prega pregi prego prema preme premi premo presa prese presi preso prete preti ' +
    'previ prima prime primi primo priva prive privi privo proba probe probi probo proda prode prodi prole proli promo prona ' +
    'prone proni prono prora prore prosa prose proti proto prova prove provi provo proxy prude pruni pruno psico psoas ptosi ' +
    'pugna pugni pugno pulce pulci pulii pulir pulli pullo pulsa pulsi pulso punch punga punge pungi pungo punir punse punta ' +
    'punte punti punto purea puree purga purgo putti putto puzza puzze puzzi puzzo quale quali quare quark quasi queen quine ' +
    'quipu quivi quota quote quoti quoto racca racco radar rader radia radio radon raffa raffi raffo rafia raggi ragia ragli ' +
    'ragni ragno raion ralli rallo rally ramai rambo ramen ramie rampa rampe rampi rampo rance ranch ranci randa rande range ' +
    'rango ranni ranno rapir rasoi raspa raspe raspi raspo ratei rateo ratio ratta ratte ratti ratto rauca rauco rayon razza ' +
    'razze razzi razzo reagi reale reali reame reami reati reato rebbi rebus recai recar rechi recto redde regga regge reggi ' +
    'reggo regia regie regio regna regni regno relax remar renai renda rende rendi rendo renio renna renne rerum ressa resse ' +
    'ressi resta reste resti resto retro retta rette retti retto reuma rezzi rezzo riamo ribes ricca ricce ricci ricco ridai ' +
    'ridar ridda rider ridia rifai rifar riffa rigar righe righi rigor rinvi rione rioni risma risme rissa risse rissi risso ' +
    'rista risti risto ritma ritmi ritmo ritta ritte ritti ritto riusa riusi riuso rivai rizza rizzi rizzo roana roane roani ' +
    'roano roast robot rocca rocce rocco roche rochi rodei rodeo roder rodia rodio rogai rogge roghi rogna rogne rolla rolli ' +
    'rollo romba rombi rombo romea romee romei romeo rompa rompe rompi rompo ronca ronda ronde ronfa ronfo ronza ronzi ronzo ' +
    'rosai rosea rosee rosei roseo roses rospi rospo rossa rosse rossi rosso rosta roste rotea rotta rotte rotti rotto rouge ' +
    'round rovai rozza rozze rozzi rozzo rubai rubar rubli rublo rugby rughe rulla rulli rullo rumba ruoli ruolo ruota ruote ' +
    'ruoti ruoto rupia rupie ruppe ruppi rusco ruspa ruspe russa russe russi russo rutta rutti rutto ruzza ruzzi ruzzo sabba ' +
    'sabbi sabea sabei sabeo sabir sabot sabra sabri sacca sacco sacra sacre sacri sacro saffo sagge saggi saghe sagra sagre ' +
    'sagri sahib salai salar salda salde saldi saldo sales salga salgo salii salir salma salme salmi salmo salpa salpe salpi ' +
    'salsa salse salsi salso salta salti salto salva salve salvi salvo samba sanai sanno sansa sanse santa sante santi santo ' +
    'sapei saper sapor sappi sarai sarda sarde sardi sardo sarei sarta sarte sarti sarto sassi sasso satin sauna saune saura ' +
    'sauri sauro savia savie savio sazia sazie sazio sbafo sbava sbavi sbavo sbuca sbuco scada scade scafa scafi scafo scala ' +
    'scale scali scalo scapi scapo scava scavi scavo scema sceme scemi scemo scena scene scesa scese scesi sceso sceva scifi ' +
    'scifo scola scoli scolo scoop scopa scope scopi scopo score scout scova scovi scovo scuce scuci scudi scudo scuoi scura ' +
    'scure scuri scuro scusa scuse scusi scuso sdrai secca secco sedai sedar seder sedia sedie segar segga seggi seggo seghe ' +
    'seghi segna segni segno segua segue segui seguo selce selci sella selle selli sello seltz selva selve selvi semel senna ' +
    'senne senni senno sensi senso senta sente senti sento senza seppe seppi sepsi serba serbe serbi serbo serge seria serie ' +
    'serio serpa serpe serpi serra serre serri serro serti serto serva serve servi servo sessa sesse sessi sesso sesta seste ' +
    'sesti sesto setta sette setti setto sfama sfami sfamo sfare sfata sfera sfere sfida sfide sfidi sfido sfiga sfila sfili ' +
    'sfilo sfizi sfoca sfoci sfoga sfogo sfora sfori sforo sfuma sfumi sfumo sfusa sfuse sfusi sfuso sgama sgami sgamo sgasa ' +
    'sgola shake shirt shock shunt siamo siano siate siche sidri sidro sieda siede siedi siedo siepe siepi sieri siero siete ' +
    'sigla sigle sigli siglo sigma silfi simun sirma sirte sirti sisma sismi sismo situa situi slama slang slava slave slavi ' +
    'slavo slega slego sloga smash smini smise smisi snack sniff snoda snodi snodo soave soavi sobri socco socia socie socio ' +
    'sodio soffi sogli sogna sogni sogno solai solar solca solco soldi soldo solea soleo solfa solfo solli sollo somma somme ' +
    'sommi sommo sonar sonda sonde sondi sondo sonia sonni sonno sopra sorba sorbe sorbi sorbo sorca sorci sorda sorde sordi ' +
    'sordo sorel sorga sorge sorgi sorgo sorra sorse sorsi sorso sorta sorte sorti sorto sosia sosta soste sosti sosto sotto ' +
    'sound sovra sozza sozze sozzi sozzo space spada spade spago spahi spala spali spana spani spano spara spare spari sparo ' +
    'spazi speck speco spedi spela speme spera speri spero spesa spese spesi speso spett spezi spiga spigo spina spine spini ' +
    'spino spira spire spiri spiro spola spole spora spore sport sposa spose sposi sposo spray sprue spuma spume spuri sputa ' +
    'sputi sputo squat squaw stadi stael staff stage staia staio stame stami stana stand stani stano stara stare stari staro ' +
    'stars start stasi staso stata state stati stato stava stavi stavo stele steli stelo steri stero stesa stese stesi steso ' +
    'stick stico stila stile stili stilo stima stime stimi stimo stipa stipe stipi stipo stira stiri stiro stiva stive stivo ' +
    'stock stola stole stoma stomi stona stoni stono stria strie strip studi stufa stufe stufi stufo stupa stupe stupi stura ' +
    'sturi sturm subbi subii subir succi succo sucre sudar sughi sugli sugna suidi suina suine suini suino suita suite sulla ' +
    'sulle sullo summa summe sunna sunti sunto suola suole suoli suolo suona suoni suono suora suore super suppa supra surah ' +
    'surra sushi susta sutra sutri svaga svago svani svaso svela sveli svelo svena sveni sveno sveva sveve svevi svevo sviar ' +
    'svita sviti svito swing tabla tacca tacce tacci tacco tacer tachi taffi tagli taide taiga taine taira talco talea talee ' +
    'talla talle talli tallo talpa talpe tamia tamil tanca tanfo tanga tange tangi tango tanna tanni tanno tanta tante tanti ' +
    'tanto tapis tappa tappe tappi tappo tarai tarda tarde tardi tardo targa targo tarla tarle tarli tarlo tarma tarme tarmi ' +
    'tarmo tarpa tarsi tarso tasca taser tassa tasse tassi tasso tasta taste tasti tasto tatti tatto tatua tatui tatuo tauri ' +
    'tauro tazza tazze teano tebea tecca teche tecla tecno tedia tedio tegea teina teine telai telex temer tempi tempo tenar ' +
    'tenda tende tendi tendo tener tenga tengo tenia tenie tenne tenni tenno tenor tensa tense tenta tenti tento tenue tenui ' +
    'teppa terga tergi tergo terme termo terna terne terni terno terra terre tersa terse tersi terso terza terze terzi terzo ' +
    'tesla tessa tesse tessi tesso testa teste testi testo tetra tetre tetri tetro tetta tette tetti tetto theta tiara tiare ' +
    'tiaso tibet tibia tibie tiene tieni tigli tigna tigra tigre tigri tigro tilde tilla tille timeo timer timor timpa timpe ' +
    'tinca tinga tinge tingi tingo tinse tinta tinte tinti tinto tirai tirar tirsi tirso tisia tizia tizie tizio tizzi tizzo ' +
    'tmesi toast tocai tocca tocco toghe togli tokaj tolda tolga tolgo tolse tolsi tolta tolte tolti tolto tomba tombe tombi ' +
    'tombo tomie tonda tonde tondi tondo toner tonfa tonfi tonfo tonia tonna tonne tonni tonno tonta tonte tonti tonto topoi ' +
    'toppa toppe torah torba torbe torca torce torci torco tordi tordo torio torma torme torna torne torni torno torre torri ' +
    'torse torsi torso torta torte torti torto torva torve torvi torvo tosar tosca tosco tossa tosse tossi tosta toste tosti ' +
    'tosto totem totip tozza tozze tozzi tozzo trace traci trago trait trama trame trami tramo trans trave travi trema tremi ' +
    'tremo trend treni treno trevi trias trico triga trina trine trini trino trita trite triti trito trivi troia troie troll ' +
    'troni trono tropi tropo trota trote trova trovi trovo truce truci truck trust tucul tuffa tuffi tuffo tulio tulle tuona ' +
    'tuoni tuono tupac turba turbe turbi turbo turca turco turma turna turni turno turpe turpi tutor tutta tutte tutti tutto ' +
    'tuzia tweet twill twist ubbia ubbie ubica uccel udine udire udita udite uditi udito udiva udivo udrai uggia ugola ugole ' +
    'ugual ulani ulano ulite uliti uliva ulive ulivi ulivo ultra ulula ululi ululo umana umane umani umano umbra umbre umbri ' +
    'umbro umica umici umico umida umide umidi umido umile umili umore umori unari unger unica unici unico unimi unire unita ' +
    'unite uniti unito univa univo upupa upupe urani urano urati urato urger urici urico urina urine urini urino urlai urlar ' +
    'urlio usala usale usali usalo usami usane usano usare usata usate usati usato usava usavi usavo uscia uscii uscio uscir ' +
    'usino usura usure uteri utero utile utili uxori vacca vacci vacua vacue vacui vacuo vaduz vaffa vagai vagar vaghe vaghi ' +
    'vagli vague valer valga valgo valle valli vallo valsa valse valsi valso valva valve vammi vampa vampe vanga vango vanne ' +
    'vanno vanta vanti vanto vapor varca varco varea varia varie vario vasai vasca vasta vaste vasti vasto vatti vecce veder ' +
    'vegli velar velia velie velli vello velma venda vende vendi vendo venga vengo venia venie venir venne venni venti vento ' +
    'verbi verbo verde verdi verga vergo verme vermi verri verro versa verse versi verso verta verte verti verto verve verza ' +
    'verze vesce vespa vespe vessa vessi vesta veste vesti vesto vetri vetro vetta vette vezzi vezzo viado viale viali viari ' +
    'vibra vibri vibro vichi video viene vieni vieta vieti vieto vigli vigna vigne villa ville villi villo vinai vinca vince ' +
    'vinci vinco vinse vinsi vinta vinte vinti vinto viola viole violi violo virga virus visco visir visnu vispa vispe vispi ' +
    'vispo visse vissi visso vista viste visti visto visus vitae vitro vitta vitte vitti vitto vivai viver vizia vizio vizza ' +
    'vizze vizzi vocio vodka vodke voile volai volar volei voler volga volge volgi volgo volle volli volpe volpi volse volsi ' +
    'volta volte volti volto votai votar vulci vulva vulve vuole vuota vuote vuoti vuoto wafer wagon water xciii xcvii xeres ' +
    'xliii xlvii xviii xxiii xxvii xxxii xxxiv xxxix xxxvi yacht yucca zaffo zaini zaino zampa zampe zanca zanna zanne zanni ' +
    'zappa zappe zappi zappo zebra zebre zecca zenit zeppa zeppe zeppi zeppo zilli zillo zinco zinna zinne zitta zitte zitti ' +
    'zitto zizza zizze zolfi zolfo zolla zolle zombi zonzo zooma zoppa zoppe zoppi zoppo zozza zozze zuava zuavi zuavo zucca ' +
    'zuffa zuffe zuppa zuppe zuppi zuppo'
  ).split(' ');
});
